### ISSUE TITLE
Draw the interactive chart with ggplot2 or plotly

### ISSUE THREAD

**Issue by chendiva** [chendiva/final-project#4]

**Comment by chendiva** [comment]
I can help with some of the part in this mission

**Comment by doreeenn206** [comment]
I can do this portion of the project.

**Comment by chendiva** [comment]
i have drawn the interactive bubble plot for the surgery of every hospital

**Comment by chendiva** [comment]
I finished the bar chart for state level surgery, but something is weird about my text, so I may make some changes next time. Gonna to ask the TA for that question

**Comment by chendiva** [comment]
Gonna to finish the pie chart for the single hospital tonight

**Comment by chendiva** [comment]
I finished a pie chart that shows the proportion of procedures based on the hospital you choose

**Comment by chendiva** [comment]
will do the markdown in the following days

**Comment by chendiva** [comment]
I have put comment on my program so that make it clear when others want to read it, and I also made some changes to the pie chart

**Comment by chendiva** [comment]
I finished comment my program, but I have a little problem on my bar chart which i want to change after asking the TA tomorrow. but all the other's are done

**Comment by chendiva** [comment]
I changed the bar name of the graph and the title of the graph to make them clearer for the readers

**Comment by chendiva** [comment]
i take off the text part of the bar graph since it just doesn't work for an unknown reason(even though I have asked the TA, this still cannot be solved)
